censof/ansible-deployment

.travis.yml, django_app_server_db_server/deployment/group_vars/all, django_app_server_db_server/deployment/hosts, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml, django_app_server_db_server/deployment/tests/hosts, test_image/Dockerfile.centos6
Added and travis is now working. closes #3
=> 3 20160527 encrypted travis env

.travis.yml, test_image/Dockerfile.centos6
Install serverspec also fixes #11
=> 11 20160531 adding task to do sysctl tuning

django_app_server_db_server/deployment/files/eclaim_nginx.conf, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml, tests/spec/test_ansible_spec.rb
=> re #15 Adding django related items

django_app_server_db_server/deployment/group_vars/app_server, django_app_server_db_server/deployment/roles/app_server/tasks/django.yml, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml
Django related tasks fixes #15
=> 15 20160603 adding tasks for django

django_app_server_db_server/deployment/roles/app_server/tasks/django.yml, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml, django_app_server_db_server/deployment/templates/eclaim.conf, django_app_server_db_server/deployment/templates/environment, django_app_server_db_server/deployment/templates/uwsgi, django_app_server_db_server/deployment/templates/uwsgi.ini, tests/spec/test_ansible_spec.rb
Add some missing files namely `uwsgi` related files plus `nginx` configurations. Also added serverspec tests for these items.
=> 19 20160609 add missing requirements

.travis.yml, django_app_server_db_server/deployment/group_vars/all, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml
=> 23 20160610 default value for eclaim build

.travis.yml, django_app_server_db_server/deployment/group_vars/all, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml
24 add branch variable from shippable.
=> 24 add variable of branch

django_app_server_db_server/deployment/roles/app_server/tasks/main.yml, django_app_server_db_server/deployment/roles/common/tasks/main.yml, django_app_server_db_server/deployment/templates/common.py, django_app_server_db_server/deployment/templates/eclaim.conf
=> Correct problems with install. #27

django_app_server_db_server/deployment/handlers/app_server/main.yml, django_app_server_db_server/deployment/main.yml, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml, tests/spec/test_ansible_spec.rb
=> 29 20160613 create event handler for uwsgi

.gitignore, .travis.yml, django_app_server_db_server/deployment/group_vars/app_server, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml
Edited the script to work with eClaim v1.0
- During running the command make sure pass variable for django_app_home & app_version to ensure install in correct path & version for it.
=> 22 20160614 deployment script for ypj

django_app_server_db_server/deployment/roles/db_server/tasks/main.yml, django_app_server_db_server/deployment/templates/postgresql.conf
Making configuration getting memory via ansible variables.
=> 38 20160620 making getting memory for db server dynamic

.travis.yml, django_app_server_db_server/deployment/roles/app_server/tasks/django.yml, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml, tests/python/verify_image.py
=> 39 20160621 fixing login

django_app_server_db_server/deployment/roles/app_server/tasks/django.yml, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml, tests/python/verify_image.py
re #46 adding `compilemessages` to deployment.
=> 46 20160625 adding django admin compilemessages

django_app_server_db_server/deployment/roles/app_server/tasks/eclaim.yml
=> re #48 merging gettext requirement into main.yml

tests/python/verify_image.py
=> Fixing build. re #54

README.md
=> Adding status badge for build. re #9

.travis.yml
=> 62 20160815 change yum to generic package

django_app_server_db_server/deployment/roles/app_server/tasks/eclaim.yml, django_app_server_db_server/deployment/roles/app_server/tasks/eclaim_revamp.yml, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml
=> re #74 removing harakiri from uwsgi.ini

django_app_server_db_server/deployment/templates/eclaim.conf, tests/python/verify_image.py
=> 86 200160907 update test verify image

django_app_server_db_server/deployment/roles/db_server/tasks/RedHat.yml
=> re #94 move the restart of postgresql after over writing configs. 

django_app_server_db_server/deployment/roles/app_server/tasks/Debian.yml, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml, django_app_server_db_server/deployment/roles/db_server/tasks/Debian.yml, django_app_server_db_server/deployment/roles/db_server/tasks/main.yml
=> 98 20160919 adding root to sudoers

django_app_server_db_server/deployment/roles/app_server/tasks/RedHat.yml
=> Enable root sudo on app_server. re #98

tests/spec/test_ansible_spec.rb
=> re #85 ubuntu and redhat support for serverspec

pre_install.sh
=> re #109 fixing version in pre_install.sh for miniconda

README.md, django_app_server_db_server/deployment/group_vars/all
=> 125 20161006 adding default value for django app home

django_app_server_db_server/deployment/roles/app_server/tasks/main.yml, django_app_server_db_server/deployment/templates/gossRedHat.json, django_app_server_db_server/deployment/templates/gossUbuntu.json
=> Test merge with master

.travis.yml, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml, tests/python/verify_image.py
=> 142 20161031 changes to common py

django_app_server_db_server/deployment/roles/app_server/tasks/Debian.yml, django_app_server_db_server/deployment/roles/app_server/tasks/RedHat.yml, django_app_server_db_server/deployment/roles/app_server/tasks/cron.yml, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml, django_app_server_db_server/deployment/templates/UpldCFBudgetSSH.sh, django_app_server_db_server/deployment/templates/UpldCFEmploySSH.sh, tests/spec/test_ansible_spec.rb
=> 147 20161115 adding saga cronjobs

django_app_server_db_server/deployment/files/pg_hba.conf, django_app_server_db_server/deployment/roles/app_server/tasks/django.yml, django_app_server_db_server/deployment/templates/settings.py
=> 159 20170106 tighten pg hba conf

.travis.yml, django_app_server_db_server/deployment/roles/db_server/tasks/main.yml
change shamall value in /etc/sysctl.conf
=> 170 20170329 postgres shared memory shmmax and shmall

django_app_server_db_server/deployment/roles/app_server/tasks/RedHat.yml, django_app_server_db_server/deployment/roles/app_server/tasks/eclaim_revamp.yml, django_app_server_db_server/deployment/roles/app_server/tasks/main.yml, django_app_server_db_server/deployment/roles/db_server/tasks/main.yml, django_app_server_db_server/deployment/templates/informix.sh, django_app_server_db_server/deployment/templates/postgresql.conf
add /opt/IBM/informix/bin in bashrc and bash_profile
=> Add /opt/IBM/informix to bashrc and bash_profile
